version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

  client:
    image: client
    build: 
        context: ../frontend
        dockerfile: Dockerfile

